name: Auto Comment
description: Auto comment issues or PRs on events triggered.
author: bubkoo <bubkoo.wy@gmail.com>

inputs:
  GITHUB_TOKEN:
    description: Your GitHub token for authentication
    required: true

  issuesOpened:
  issuesEdited:
  issuesDeleted:
  issuesTransferred:
  issuesPinned:
  issuesUnpinned:
  issuesClosed:
  issuesReopened:
  issuesAssigned:
  issuesUnassigned:
  issuesLabeled:
  issuesUnlabeled:
  issuesLocked:
  issuesUnlocked:
  issuesMilestoned:
  issuesDemilestoned:
  pullRequestAssigned:
  pullRequestUnassigned:
  pullRequestLabeled:
  pullRequestUnlabeled:
  pullRequestEdited:
  pullRequestOpened:
  pullRequestClosed:
  pullRequestReopened:
  pullRequestSynchronize:
  pullRequestReadyForReview:
  pullRequestLocked:
  pullRequestUnlocked:
  pullRequestReviewRequested:
  pullRequestReviewRequestRemoved:

  issuesOpenedComment:
  issuesEditedComment:
  issuesDeletedComment:
  issuesTransferredComment:
  issuesPinnedComment:
  issuesUnpinnedComment:
  issuesClosedComment:
  issuesReopenedComment:
  issuesAssignedComment:
  issuesUnassignedComment:
  issuesLabeledComment:
  issuesUnlabeledComment:
  issuesLockedComment:
  issuesUnlockedComment:
  issuesMilestonedComment:
  issuesDemilestonedComment:
  pullRequestAssignedComment:
  pullRequestUnassignedComment:
  pullRequestLabeledComment:
  pullRequestUnlabeledComment:
  pullRequestEditedComment:
  pullRequestOpenedComment:
  pullRequestClosedComment:
  pullRequestReopenedComment:
  pullRequestSynchronizeComment:
  pullRequestReadyForReviewComment:
  pullRequestLockedComment:
  pullRequestUnlockedComment:
  pullRequestReviewRequestedComment:
  pullRequestReviewRequestRemovedComment:

  issuesOpenedReactions:
  issuesEditedReactions:
  issuesDeletedReactions:
  issuesTransferredReactions:
  issuesPinnedReactions:
  issuesUnpinnedReactions:
  issuesClosedReactions:
  issuesReopenedReactions:
  issuesAssignedReactions:
  issuesUnassignedReactions:
  issuesLabeledReactions:
  issuesUnlabeledReactions:
  issuesLockedReactions:
  issuesUnlockedReactions:
  issuesMilestonedReactions:
  issuesDemilestonedReactions:
  pullRequestAssignedReactions:
  pullRequestUnassignedReactions:
  pullRequestLabeledReactions:
  pullRequestUnlabeledReactions:
  pullRequestEditedReactions:
  pullRequestOpenedReactions:
  pullRequestClosedReactions:
  pullRequestReopenedReactions:
  pullRequestSynchronizeReactions:
  pullRequestReadyForReviewReactions:
  pullRequestLockedReactions:
  pullRequestUnlockedReactions:
  pullRequestReviewRequestedReactions:
  pullRequestReviewRequestRemovedReactions:

runs:
  using: node12
  main: dist/index.js

branding:
  icon: send
  color: green
